version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tasq-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  envoy:
    image: envoyproxy/envoy:v1.27-latest
    hostname: envoy
    container_name: tasq-proxy
    ports:
      - '8080:8080'
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

volumes:
  db_data:
